{
 "title": "Arena_kpi",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 12, "x": 0, "y": 0 },
   "options": {
    "content": "<h1 style=\"text-align:center;\">Tanger 1</h1>"
   },
   "targets": [
    { "dataset": "arena1" }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 12, "x": 12, "y": 0 },
   "options": {
    "content": "<h1 style=\"text-align:center;\">Tanger 2</h1>"
   },
   "targets": [
    { "dataset": "arena1" }
   ]
  },
  {
   "title": "Etat de MACHINE 1",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "arena1",
     "rawSql": "SELECT STATE_M1 FROM arena1.sim_data1 LIMIT 140"
    }
   ]
  },
  {
   "title": "Etat de MACHINE 2",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "arena1",
     "rawSql": "SELECT STATE_M2 FROM arena1.sim_data1 LIMIT 140"
    }
   ]
  },
  {
   "title": "Etat de MACHINE 1",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "dataset": "arena1",
     "rawSql": "SELECT STATE_M1, DATE FROM arena1.sim_data1 LIMIT 50 "
    }
   ]
  },
  {
   "title": "Etat de Machine 2",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "targets": [
    {
     "dataset": "arena1",
     "rawSql": "SELECT DATE, STATE_M2 FROM arena1.sim_data1 LIMIT 50 "
    }
   ]
  },
  {
   "title": "Le nombre de sortie dU MACHINE 1",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "dataset": "arena1",
     "rawSql": "SELECT NB_OUT_M1, DATE FROM arena1.sim_data1 LIMIT 50 "
    }
   ]
  },
  {
   "title": "Nombre de Sortie de M2",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "targets": [
    {
     "dataset": "arena1",
     "rawSql": "SELECT NB_OUT_M2, DATE FROM arena1.sim_data1 LIMIT 50 "
    }
   ]
  },
  {
   "title": "Current  Queue ",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "arena1",
     "rawSql": "SELECT CURRENT_QUEUE FROM arena1.sim_data1 LIMIT 50 "
    }
   ]
  },
  {
   "title": "Lead Time Average ",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "arena1",
     "rawSql": "SELECT AVG(LEAD_TIME) FROM arena1.sim_data1 LIMIT 130"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 27 },
   "targets": [
    {
     "dataset": "arena1",
     "rawSql": "SELECT `N°`, DATE, NB_OUT_M1, NB_OUT_M2, STATE_M1, STATE_M2, CURRENT_QUEUE, LEAD_TIME FROM arena1.sim_data1 LIMIT 140"
    }
   ]
  }
 ]
}